In [3]:
#Q1 Create a numpy array starting from 2 till 50 with a stepsize of 3.

import numpy as np

arr = np.array(np.arange(2,51,3))
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [40]:
#Q2 Accept two lists of 5 elements each from the user.Convert them to numpy arrays. 
#Concatenate these arrays and print it. Also sort these arrays and print it.

l1 = []
l2 = []
print("Enter 5 numbers for list1")
for i in range(5):
    l1.append(int(input()))
    
print("Enter 5 numbers for list2")
for i in range(5):
    l2.append(int(input()))

arr1 = np.array(l1)   #Converting list1 to array
arr2 = np.array(l2)   #Converting list2 to array
print("Array1 : ",arr1)
print("Array2 : ",arr2)
arr3 = np.concatenate((arr1,arr2),axis=None)    #Concatinating both arrays
print("After Concatenation : ",arr3)     #Sorting concatinated arrays
arr3.sort()
print("After sorting : ",arr3)

Enter 5 numbers for list1
5
3
6
3
7
Enter 5 numbers for list2
5
3
7
4
2
Array1 :  [5 3 6 3 7]
Array2 :  [5 3 7 4 2]
After Concatenation :  [5 3 6 3 7 5 3 7 4 2]
After sorting :  [2 3 3 3 4 5 5 6 7 7]


In [ ]:
#Q3 Write a code snippet to find the dimensions of a ndarray and its size.

arr = np.arange(12).reshape(3,4)
print("Array:\n",arr)
print("\nArray Dimension: ",arr.ndim)
print("\nArray size : ",arr.size)

In [42]:
#Q4 How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

#For newaxis
arr = np.arange(12)
print(arr)
print("\nShape before newaxis: ",np.shape(arr))
arr1 = arr[np.newaxis,:]    #By using newaxis
print(arr1)
print("\nShape after newaxis: ",np.shape(arr1))

#For expand_dims
arr2 = np.arange(12)
print(arr2)
print("\nShape before expand_dims: ",np.shape(arr2))
arr3 = np.expand_dims(arr2,axis=0)   #By using expand_dims
print(arr3)
print("\nShape after newaxis: ",np.shape(arr3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

Shape before newaxis:  (12,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

Shape after newaxis:  (1, 12)
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Shape before expand_dims:  (12,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

Shape after newaxis:  (1, 12)


In [33]:
#Q5 Consider two square numpy arrays. Stack them vertically and horizontally.

arr1 = np.arange(16).reshape(4,4)
arr2 = np.arange(16,32).reshape(4,4)
print(arr1,"\n\n")
print(arr2)
print("\nStacking horizontally")
arr3 = np.hstack((arr1,arr2))
print(arr3)
print("\nStacking vertically")
arr4 = np.vstack((arr1,arr2))
print(arr4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

Stacking horizontally
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]

Stacking vertically
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [37]:
#Q6 How to get unique items and counts of unique items?

arr = np.array([1,2,4,2,4,6,4,6,8,5,3,7])
print(arr)    #normal array
arr2 = np.unique(arr)    #Finding unique elements of this array
print(arr2)
print(len(arr2))      # Counting number of unique items

[1 2 4 2 4 6 4 6 8 5 3 7]
[1 2 3 4 5 6 7 8]
8
